<?php

/**
 * @file
 * Contains claims.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function claims_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the claims module.
    case 'help.page.claims':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Claims related functionality') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function claims_theme($existing, $type, $theme, $path) {
  return [
    'claim_voucher' => [
      'variables' => ['node' => NULL],
    ],
  ];
}

/**
 * Implements hook_preprocess_node().
 */
function claims_preprocess_node(&$variables) {
  $node = $variables['node'];
  if ($node->getType() == 'partners') {
    $nid = $node->id();
    $connection = \Drupal::database();

    $query = $connection->query('SELECT voucher_code FROM {claim_codes} WHERE partner = :nid LIMIT 1', [':nid' => $nid]);
    $code = $query->fetchField();

    $variables['voucher_code'] = $code;
  }
}
